//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public int IdRoom { get; set; }
        public string RoomName { get; set; }
        public Nullable<int> chairNumber { get; set; }
        public string equipment { get; set; }
        public Nullable<bool> available { get; set; }
        public string Price { get; set; }
    }
}
